name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        sudo apt update
        sudo apt upgrade -Y 
        sudo apt install python3-pip python3-dev build-essential rabbitmq-server
        sudo pip3 install celery tensorflow==2.10.0 amqp flask==2.3.1 future numpy
        git clone https://github.com/sztoor/model_serving.git
        celery --workdir=/model_serving/single_server_without_docker/production_server -A workerA worker --detach --loglevel=debug --concurrency=1 -n wkr1@backend
        python3 /model_serving/single_server_without_docker/production_server/app.py --host=0.0.0.0 --port=5100
